/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.view;

/**
 *
 * @author ARDITI
 */
public class AnalysisFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form AnalysisFrame
     */
    public AnalysisFrame() {
        initComponents();
        this.setLocation(40,40);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        patientTxtf = new javax.swing.JTextField();
        AnalysisTxtf = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        analysisResultsTxtf = new javax.swing.JTextArea();

        setClosable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(null);
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setText("Analysis :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 130, 25));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setText("Analysis Results :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 130, 25));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel3.setText("Patient :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 130, 25));
        getContentPane().add(patientTxtf, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 250, 25));
        getContentPane().add(AnalysisTxtf, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 250, 25));

        analysisResultsTxtf.setColumns(20);
        analysisResultsTxtf.setLineWrap(true);
        analysisResultsTxtf.setRows(5);
        analysisResultsTxtf.setWrapStyleWord(true);
        jScrollPane1.setViewportView(analysisResultsTxtf);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 250, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AnalysisTxtf;
    private javax.swing.JTextArea analysisResultsTxtf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField patientTxtf;
    // End of variables declaration//GEN-END:variables
}
